-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_api_request_track`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_api_request_track
-- *
-- * Api Request Tracker
-- *
-- *******************************************************/
CREATE TABLE `civicrm_api_request_track` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique ApiRequestTrack ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `entity` varchar(255) NULL,
  `action` varchar(255) NULL,
  `response` text NULL,
  `errorMessage` varchar(255) NULL,
  `errorCode` varchar(255) NULL,
  `apiVersion` varchar(255) NULL,
  `created_date` datetime COMMENT 'Date and time that request was created.',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_api_request_track_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
